### ISSUE TITLE
実行ボタンがあるなら押したい。

### ISSUE THREAD

**Issue by take-cheeze** [cpprefjp/kunai#24]
`Compile` 扱いですが、disableとはいえあるものは押したい

ref:
https://github.com/cpprefjp/site/issues/473#issuecomment-341327815

**Comment by saki7** [comment]
今は、 一番左の「Try Code」のボタンを押すとエディタが有効化されて、有効な状態で「Compile」を押すと実行出来るようになっています。

無効化されている時に「Compile」を押したら自動でエディタを有効化したい、という認識で合っていますか？　あるいは、ブラウザにバグがあって僕の環境とは違う挙動をしているのかもしれません。

**Comment by take-cheeze** [comment]
> 無効化されている時に「Compile」を押したら自動でエディタを有効化したい、という認識で合っています

 はい。Try Code押してから表示されるでもよいです。
単にあると押したくなる病なので。

**Comment by saki7** [comment]
なるほど。この辺の見せ方は少し考えます。

僕は従来のシンタックスハイライトは保持しておきたくて、そこでワンアクションあってから切り替えたいと考えているのですが、「有効化ボタン」を1個置いておくだけだと”そのまま実行できる”というイメージがあまり出なくて、今の感じになっています。

**Comment by yumetodo** [comment]
`Try Code`を押すまで`Compile`を`Display: none;`にしてしまうのはどうでしょう

**Comment by saki7** [comment]
@yumetodo それは良い案だと思います。僕もそれを含めて色々考えてます

**Comment by saki7** [comment]
@take-cheeze こういう風にしてみましたがどうですか？ これで特に違和感がないようであれば close していただけると……

![peek 2017-11-04 12-15](https://user-images.githubusercontent.com/1901813/32401803-ee7d4086-c159-11e7-805b-2f0007d12c31.gif)

**Comment by saki7** [comment]
あ、ちなみにこれ本番環境で見れます。

**Comment by take-cheeze** [comment]
@saki7 ありがとうございます 👍

**Comment by saki7** [comment]
:sparkles:
