### ISSUE TITLE
重い

### ISSUE THREAD

**Issue by saki7** [cpprefjp/kunai#25]
2800ページ分のDOMを生成してるので遅延評価したい

非同期にはしているけど重すぎ

**Comment by yumetodo** [comment]
当方環境ではDOMContentLoad: 1.22秒、load: 5.41秒と、DOMContentLoadからloadまでが長すぎる。
パフォーマンス解析によればDOMContentLoadのあとのCSS再計算のあとに1秒近いkunaiに起因するDOMイベント(kunai-vender.js;24)が発生しており、これが終わるまで以降のネットワーク読み込みがblockされている。

**Comment by saki7** [comment]
kunai-vendor内のDOMイベントは間違いなくjQueryのDOM周りなので、やはりこれはKunai側で遅延評価しないと意味ないっすね。

**Comment by saki7** [comment]
@yumetodo 重さは一旦置いとくとしても、最大限asyncすることでネットワーク読み込みがブロックされるのは回避できるはずなのでブロックされてるということはasyncが足りてないはずなので、そのへんのプロファイルのデータがあればここに貼っていただけると……

**Comment by yumetodo** [comment]
ブロックされていると言うのは誤解だったというか、Googleカスタム検索周りのブロッキングをkunaiのと読み間違えていました。

profileは
https://gist.github.com/yumetodo/3125a8a840ce7d6a7ebac1ad5b03cdf6
です、Firefoxで開いてください。

**Comment by saki7** [comment]
Googleカスタム検索はそもそも使っている人がいなさそうなのでいっそのこと消そうかと考えてます。というか、ここ数日の大幅な変更の副作用で見た目が吹っ飛んでるので、今使えてる人は居ないはずです。

**Comment by saki7** [comment]
まあ、カスタム検索については今考えることではないので、とりあえず修正はしておきます。
