### ISSUE TITLE
iPhone 7のiOS 10のSafariでサイドバーのみが表示されてメインコンテンツが表示されない

### ISSUE THREAD

**Issue by saki7** [cpprefjp/kunai#33]
https://github.com/cpprefjp/site/issues/476#issuecomment-342754140

> iPhone 7のiOS 10のSafariブラウザ環境で、サイドバーのみが表示されメインコンテンツが表示されない問題がありました。iOS 11に上げたら直りました。

**Comment by saki7** [comment]
#31 （既に本番に反映されている）で直ったはず

@faithandbrave 実機で確認して頂けますか？

**Comment by faithandbrave** [comment]
OSのバージョンを上げてしまいましたが、iOS 11ではいま問題ないです。

**Comment by saki7** [comment]
おっけーです。限定的な条件の検証ですが、iOS 10ベースの表示でもサイドバーがページの一番下に飛ばされている（想定している動作）なので多分直ってると思います。 :space_invader:

**Comment by saki7** [comment]
> おっけーです。限定的な条件の検証ですが、iOS 10ベースの表示でもサイドバーがページの一番下に飛ばされている（想定している動作）なので多分直ってると思います。 :space_invader:

どんなローカル環境でも無条件で「デスクトップでは左＋右、モバイルでは上＋下」になるのがkunaiのcss類で想定している動作なので、これが実際に正しくデプロイされていれば、内容が崩れているか崩れていないかにかかわらず、上下／左右の配置は守られるはずです。なので、掲題のような問題は #31 によって再発しないようになりました。
