### ISSUE TITLE
サイドバー項目見出し中の `std::` が大きな面積を占めている

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/kunai#43]
サイドバーの各項目見出し中の `std::` が単独の行に表示されて大きな縦幅を
とっていて、その結果として画面内に収まる項目数が大きく削られてしまって
いました。 (Firefox 56.0)

`std::` 直下の項目数が多い `<algorithm>` などを展開したときが顕著です。
Legacy sidebar では `std::` の表示はありませんでした。

消してしまうか `std::adjacent_find` のように１行にまとめて表示することが
できればサイドバーの使い勝手が良くなりそうです。

**Comment by saki7** [comment]
今のフロントエンドでは、「全てのページをヘッダファイルでグルーピング」「ヘッダファイル内の全てのページをクラスをそれ以外でグルーピング」という実装になっています。名前空間でグルーピングしてソートする処理自体が入っていないので実装に時間がかかりますが、対応したいと思います

**Comment by saki7** [comment]
かかる作業量が半端ないので未来に希望を託したい

**Comment by melpon** [comment]
とりあえず横に並べて表示するようにしてみました。どうでしょうか。

**Comment by k-satoda** [comment]
１行にまとめて表示されるようになってるのを確認しました。
問題なくなったと思います。ありがとうございます。
