### ISSUE TITLE
サイドバーの項目をロード時に表示ページにあわせて展開

### ISSUE THREAD

**Issue by k-satoda** [cpprefjp/kunai#44]
ロード時にサイドバーの項目がすべて畳まれてしまうと、同階層の項目を
「これかな？・・・違った。じゃぁ・・・」という感じで順に開いていくような
見方はしづらくなっているようでした。  (Firefox 56.0)
（ `<algorithm>` の関数や `basic_string` のメンバ関数でよくありそう。）

Legacy sidebar では表示中の項目がツリー中に表示されるように展開された
状態になっていて、比較的そういった見方がしやすかったように思います。

**Comment by saki7** [comment]
これは手元では半分くらい実装しました。Sidebar v2の期限までにはデプロイ出来ると思います。

これにプラスしてサイドバーを左に固定することでナビゲーションはかなり改善される気がしています
