### ISSUE TITLE
コンソールのデバッグログが重すぎる

### ISSUE THREAD

**Issue by saki7** [cpprefjp/kunai#61]
これはnagatoの問題で、Chrome以外のConsole APIの実装がゴミすぎ

**Comment by saki7** [comment]
デバッグログが綺麗に出ないと開発のモチベーションが全く上がらないのでnagatoというロガーをとりあえず作って運用してるけど、開発にChrome以外を使う人もいそうなので緊急度が高ければどうにかする

本番でデバッグレベルinfo以上が表示されるのは意図した仕様

**Comment by yumetodo** [comment]
いや、デバッグログはgetパラメータに`?debug=1`とかついている時だけにできないもんでしょうか。

**Comment by saki7** [comment]
出来ないし、やるつもりもないです。本番環境で最低限のログが常に出ていないとバグレポのモチベーションが出ない。

**Comment by yumetodo** [comment]
```js
new URL(window.location.href).searchParams.get("debug");
```
的な何かで判定できると思ったんですが、モチベーションは理解できる・・・

**Comment by saki7** [comment]
@yumetodo クエリ文字列に別のものが付いた時点でそれは別のURLなので、同じページが表示されていたとしてもそれはGitHub Pagesの仕様なだけでHTTPとしては別物です（言いたいことは分かりますが俺が言うことの粗探しを毎回されるのが普通に不快なのでやめてください）

**Comment by faithandbrave** [comment]
@yumetodo さんは思いつきで言ってるのか、協力したいから言ってるのかがよくわからないのが問題ですね。
思いつきレベルなら、開発の妨げになるような議論の仕方は避けてください。大きな目的を達成するために小さな手段の違いを議論するのは体力を消耗するだけです。
協力したいから言っているのであれば、まずそれを宣言した上で方針の確認として質問したほうがよいと思います。
あまり続くようなら、 @yumetodo さん用に議論の仕方についてのガイドラインを設けることになりますが、それはコントリビュートのハードルを上げることになるのでできればしたくありません。ですので、まず議論の仕方を学んだほうがよいと思います。
参考として、以下の記事がよくまとまっているので参照してみてください。

- [『議論パターン』～不毛な議論を避け、実り有る議論とするために～](http://www.shos.info/develop/oo/dscsnptn.html)

**Comment by saki7** [comment]
@yumetodo 

kunaiの以前のPRでも書きましたが、Issue/PRを立てる際は「動機」を明確にしてください。

それはどんなに些細な個人的事情でも構いませんし、動機は動機であるのでそれが正しいとか間違っているということはありません。

しかし、解決策としての手法について議論する時に、正しいか正しくないか、別の方法があるかないかという点は、動機が明らかでない場合は単なる重箱の隅です。

僕は、少なくとも今までのコメントでは「動機」を明らかにするという点を非常に意識してきました。

たとえば、このIssueのコメントの例では、

> デバッグログが綺麗に出ないと開発のモチベーションが全く上がらないのでnagatoというロガーをとりあえず作って運用

ここで、「デバッガーを自作している動機」を説明しています。

次に、

> 出来ないし、やるつもりもないです。本番環境で最低限のログが常に出ていないとバグレポのモチベーションが出ない。

ここで、本番環境でログを出す必要性について、「バグレポする人のモチベーションをあげるため」という動機があるということを説明しています。

@yumetodo さんは、今まで何度もこの既出の「動機」や「背景」を無視して、文脈が無い提案をいくつも書かれています。動機が明らかでないと、yumetodoさんのコメントを読んだ人が、どういう風に反応して良いのか分かりません。そのため、健全な議論もできません。

そういう状態が続いてしまうと、見る人が不快になるのは避けられません。

**Comment by yumetodo** [comment]
動機としてはIE11/Edge対応のためのデバッグをしていた際に動作がフリーズすることが頻発したという経緯があったのですが(モチベーションが私の中で実際下がった)、よく考えてみれば開発者ツールを使いながらEdgeを使う人なんて稀ですね。デバッグ時は(自分でWebpack回していれば)手元でログを切れないことも無いわけですし。

この件を含めた動機と背景と需要の説明不十分な点、お詫びします。

**Comment by saki7** [comment]
> 動機としてはIE11/Edge対応のためのデバッグをしていた際に動作がフリーズすることが頻発したという経緯があったのですが(モチベーションが私の中で実際下がった)、よく考えてみれば開発者ツールを使いながらEdgeを使う人なんて稀ですね。デバッグ時は(自分でWebpack回していれば)手元でログを切れないことも無いわけですし。

これを書いていただきありがとうございます。僕はもともとEdgeで開発するという視点自体が抜けていたのですが、Edgeのバグ対応の中でyumetodoさんがEdgeのコンソールのスクショを貼っていたことで初めてこのIssueに気づきました。

しかし、

> よく考えてみれば開発者ツールを使いながらEdgeを使う人なんて稀ですね

こういうことは僕も言っていませんし、誰も言っていません。僕はこんな風には断じて考えていません。ユーザが稀だから対応するかどうかという尺度は僕の中にありません。ユーザの数や開発者の数で変わるのは、問題の優先順位だけです。それも僕の中での個人的な優先順位であって、僕以外の人がどう受け取るかという点について僕は干渉しません。

こういう風に卑屈に考える必要はありません。僕が不快に感じたというのはyumetodoさんのコメントの書き方であって、Edgeの開発者を下に見ていることはありません。

**Comment by saki7** [comment]
そもそも、

> これはnagatoの問題で、Chrome以外のConsole APIの実装がゴミすぎ

僕のこの1番最初のコメントに書いてある通り、僕がこのIssueを立てた目的自体が、僕以外の（特にEdgeの）開発者のことを考えたためです。

だって、僕はChromeで日常的に開発していると明言していて、EdgeのIssueではEdgeの検証環境が無いとまで書いているのに、僕が全く影響が受けない問題をわざわざ開発者の僕自身が報告するモチベーションって、それしかないですよ。

> よく考えてみれば開発者ツールを使いながらEdgeを使う人なんて稀ですね

こういう風に、言ってもいないことを勝手に解釈して勝手に卑屈になられるのは、はっきり言って他のEdgeの開発者に失礼です。他のEdgeの開発者が、こういうコメントを読んだ時にどう感じるのか考えてください。

僕がコメントの書き方で不快に感じたという件は別に分かって頂ければそれで良いのですが、こういうことは本当にやめてください。

**Comment by melpon** [comment]
nagato はリポジトリが archive されてて使わないようにしたので閉じます
