### ISSUE TITLE
サイドバーでヘッダーを展開中にウィンドウの高さが小さくなると文字が重なる

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/kunai#64]
ウィンドウの高さを少しずつ小さくしていったときのスクリーンショット。Google Chrome 62.0.3202.94でのみ確認、他のブラウザで発生するかは #63 の影響で不明

1. 
![image](https://user-images.githubusercontent.com/10869046/32854666-b58e8564-ca82-11e7-91d7-3ac1b80a7df6.png)
2. 
![image](https://user-images.githubusercontent.com/10869046/32854677-ba4817a0-ca82-11e7-8331-713e1ee0eb36.png)
3. 
![image](https://user-images.githubusercontent.com/10869046/32854682-beac72b4-ca82-11e7-8beb-ba8ce730b388.png)
4. 
![image](https://user-images.githubusercontent.com/10869046/32854684-c1b6f86c-ca82-11e7-9a52-d049f9f58525.png)

**Comment by saki7** [comment]
問題はここですね https://github.com/cpprefjp/kunai/blob/190782d4c48794772f9ecb2950b5da81b5313542/css/kunai/site/layout.css#L20

**Comment by saki7** [comment]
cpprefjp の高さは、すべてこの変数で決定されています。

https://github.com/cpprefjp/kunai/blob/190782d4c48794772f9ecb2950b5da81b5313542/css/kunai/variables.css#L1-L2

ちなみに、スマホ表示になった時の幅は、CSSの `@media` によってレスポンシブに決定されます。

https://github.com/cpprefjp/kunai/blob/190782d4c48794772f9ecb2950b5da81b5313542/css/kunai/site/layout.css#L229

ただ、レスポンシブに高さを変えているコードは無かったと思います。レスポンシブに変えているのは幅とか並び順とかなので。

**Comment by saki7** [comment]
試しましたがこれはウィンドウサイズが390px以下の特殊な環境でしか問題にならないので放置します

**Comment by saki7** [comment]
念のため補足です、上のコード引用部分で使ってる `calc()` っていうのは、CSS3の動的計算関数じゃなくて、PostCSSの静的な計算関数で、全ての値がトランスパイル時に決定できない場合はエラーを吐くように設定しています、なのでそこは問題ないです（単純に 100vh - 5vh = 95vh に決定される）
