### ISSUE TITLE
「非推奨だった bool 型に対するインクリメント演算子を削除」ページのコードが実行可能になっていない

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/kunai#69]
例:
- https://cpprefjp.github.io/lang/cpp17/remove_deprecated_increment_of_bool.html

他にもあるかもしれない。

**Comment by faithandbrave** [comment]
コードブロックいくつか修正しましたが、この修正と関係なく動いていなかったところもあります。
https://github.com/cpprefjp/site/commit/689f3a975faf1c799156262c8c252587dff5e22e

**Comment by saki7** [comment]
@yumetodo コードが実行可能にならないことが問題のはずなので、コードを実行可能にすれば問題が解決すると思うのですが、何故revertしたのですか？

**Comment by faithandbrave** [comment]
あ、すいません。ぼくの修正が話をややこしくしてる気がします。
@yumetodo さんがrevertしたぼくの修正以外のところも、実行可能になっていませんでした。

@yumetodo さんがrevertしたところは、コンパイルエラーになることを意図した「削除された機能のコード」だと思います。しかし、これは方針としては「インクルードとmain関数を含む完全なコードにはexampleを付ける」というものになっていました。
Wandboxで実行することで、実際にコンパイルエラーになることを確認できるので、それも実行可能にしたほうがよいかと思います。この方針を変更したい場合は、cpprefjp/siteでIssueを立て、編集者間の合意をとってルール改定をしてください。

**Comment by saki7** [comment]
把握しました。それで、僕の認識も @faithandbrave さんと同じなので、 @yumetodo さんは、「非推奨だった bool 型に対するインクリメント演算子を削除」のページ内にある完全なコード全てに example タグをつけて頂けますか？そうすれば、全体で統一が取れて、このIssueの問題も解決すると思います。

**Comment by yumetodo** [comment]
@saki7 https://github.com/cpprefjp/site/commit/9c170bac3f29e6adfc56a5171274f968342d2facをrevertするか否かはこのIssueに関係ないです。なぜかは @faithandbrave さんが

>@yumetodo さんがrevertしたぼくの修正以外のところも、実行可能になっていませんでした。

と言及しているとおりです

**Comment by yumetodo** [comment]
>https://github.com/cpprefjp/site_generator/issues/30#issuecomment-341321281
>※念のため補足ですが、 このIssueの内容が全て実装された場合、 Kunai は md を見に行かなくなるので、 cpp example と書いたらそのまま実行可能になるわけではありません。 @melpon が <head> に JSON を入れる実装をした時点で Kunai の挙動を切り替えます。それまでは現行の挙動を保持するつもりです

あー、えっとこれは「例」の項の中にないからまだ実行可能にならないということですかね・・・？
@saki7

**Comment by yumetodo** [comment]
@faithandbrave 

>@yumetodo さんがrevertしたところは、コンパイルエラーになることを意図した「削除された機能のコード」だと思います。

違います。変数の状態がどうなっているかわからないことに前提をおいた説明をしたいからです。

>しかし、これは方針としては「インクルードとmain関数を含む完全なコードにはexampleを付ける」というものになっていました。

いつの間にそんな方針が・・・と思って見返していたら、 https://github.com/cpprefjp/site/issues/473#issuecomment-341325058 で書かれている・・・、見落としていました。

とはいえ、これは実行可能ではないと思うので
https://github.com/cpprefjp/site/issues/487
を立てました。

**Comment by saki7** [comment]
@yumetodo:

> あー、えっとこれは「例」の項の中にないからまだ実行可能にならないということですかね・・・？つまり cpprefjp/site_generator#48 待ち・・・？

https://github.com/cpprefjp/kunai/issues/69#issuecomment-349004358

これはフロントエンドの実装詳細の話なので、気にしなくて良いです。完全に実装が終わるまでは現行の判別処理を引き続き使うよということです。

現行の判別処理はこれです https://github.com/cpprefjp/kunai/blob/4ea3bbe5779d51ba4f452894d511ce2df9e64385/js/kunai/meta/meta.js#L150-L152

---

example を付ける場面についてはIssueが分離したので 487 の方に書きます

**Comment by saki7** [comment]
この件はkunaiには問題はないのですが、いまさらIssueを移動するのもアレなのでこのまま続けますが、タイトルは変えます。

cpprefjp/site#488 の対応で漏れが無くなったと思いますが、 「非推奨だった bool 型に対するインクリメント演算子を削除」ページの example タグはrevertされたままなので、コンフリクトを防ぐためにここへのexampleタグへの追加は @yumetodo さんにお願いします。

ここにexampleタグを付けたい背景は https://github.com/cpprefjp/site/issues/487#issuecomment-349156225 で書いた通りです。対称性のため、「非推奨だった bool 型に対するインクリメント演算子を削除」のコード片にも exampleタグを付けてください。

**Comment by yumetodo** [comment]
>「非推奨だった bool 型に対するインクリメント演算子を削除」ページの example タグはrevertされたままなので

全部exampleタグが外れているわけではありません。

現状ついているものすら実行可能にならないことについて改めて原因を教えてください。

**Comment by saki7** [comment]
あー。原因分かりました。これ（付いているのに表示されないもの）は実装のバグなのでIssue立てます

**Comment by yumetodo** [comment]
>exampleタグへの追加は @yumetodo さんにお願いします。

現在自分の過去すべての編集を遡って確認中です。

>実装のバグなのでIssue立てます

わかりました。

**Comment by saki7** [comment]
途中「kunaiに問題ない」とか書いてたのは、単純に全てのexampleタグを削除したために丸ごと消えているものだと早とちりしていました。なので、このIssueで微妙にすれ違いみたいなのがあったのは僕が勘違いしてたからです。

**Comment by yumetodo** [comment]
@saki7 やっぱりすれ違っていましたか。とりあえずこのIssueは https://github.com/cpprefjp/site/commit/fcf8708879adcbb7dfc0a577fd207dbf96ce8f35 を持って閉じ、バグについては #71 へ。

**Comment by saki7** [comment]
cpprefjp/kunai#74 で直ったと思う（本番に反映済） @yumetodo

**Comment by yumetodo** [comment]
確認しました。
