### ISSUE TITLE
検索枠をもう少し目立たせて欲しい

### ISSUE THREAD

**Issue by S-H-GAMELINKS** [cpprefjp/kunai#77]
ページ右上にあります検索枠が少し見えにくいのではと思います。
モニターの明るさなどにもよりますが、検索枠の周辺と背景色とが重なって見え、真っ白のように見えることがあります。

特に、長時間調べ物をしている時ですと目が疲れていることもあり、一瞬「どこに検索エンジンあったっけ？」となることもあります。

検索枠をもう少し目立つようにすることでUXの向上が見込めるのではないかと思います。

ref : https://pawoo.net/@yumetodo/59840749

**Comment by yumetodo** [comment]
試しに`#87CEEB`の補色ということで`#eba487`を入れてみたけど悪くなさそう・・・？
![image](https://user-images.githubusercontent.com/10869046/34076555-4f937552-e32e-11e7-8252-c36631b7f3ae.png)

**Comment by melpon** [comment]
自分としては、「どこに検索エンジンあったっけ？」となったことが無いのでよく分からず、かつ補色にしたことでそんな変わってるように見えないので解決してるかどうかも分からない状態です。

とりあえず、デザインが悪く無さそうなら @yumetodo さんが書いた通り直してみようと思いますが、これで解決しそうなんですかね？

**Comment by S-H-GAMELINKS** [comment]
はい。これで検索枠が視認しやすくなったと思います。

**Comment by melpon** [comment]
まだ kunai 側で取り込んでいないので Reopen

**Comment by melpon** [comment]
kunai 側で取り込んで無事直ったので Close します。
