### ISSUE TITLE
コードサンプル実行: Try Code ボタンが別のコードブロックに表示される

### ISSUE THREAD

**Issue by akinomyoga** [cpprefjp/kunai#78]
以下のページで起こっている問題です。Chrome 63.0.3239.84 / Firefox 57.0.2 (on Win 10) で確認しました。

* http://cpprefjp.github.io/lang/cpp11/char16_32.html
* http://cpprefjp.github.io/lang/cpp11/utf8_string_literals.html

リスト内に ```` ```cpp ～``` ```` があるとき、

1. Try Code ボタンが表示されるコードブロックが一斉にずれています。
2. また Try Code ボタンを再度押して実行モードを閉じたとき、出力枠が表示されたまま残ってしまいます。

(ちゃんと調べていないのですが、恐らく kunai の問題だろうと思ってここに書きます。違っていたらすみません)

**Comment by yumetodo** [comment]
うわ、ずれている・・・。

`data-kunai-yata-id`の付与に問題がありそうですね。一番最初のコードブロックにこれが付与されていないので。

**Comment by faithandbrave** [comment]
リストの深い階層で実行するのは見た目もよくないと思うので、リスト内では`example`を付けないようにします。

**Comment by yumetodo** [comment]
@faithandbrave それだと`example`タグ導入の理念に反しませんか？

**Comment by faithandbrave** [comment]
http://cpprefjp.github.io/lang/cpp11/utf8_string_literals.html

ここのページはリスト内に非exampleのサンプルコードがありますが、それによってずれているので、exampleを外せば済む問題ではなさそうです。

**Comment by akinomyoga** [comment]
@faithandbrave 今回私が発見した範囲ではリスト内にコードブロックを置かなければ問題に蓋はできますが、他のパターンで問題が発生する可能性は排除できませんね…。また、"リスト内にコードブロックは置いてはならない" / "リスト内のコードブロックには example を指定しない" などの不自然な編集規則を導入するのも編集の取り決めが複雑化するので、根本的な解決をした方が良いように感じます

**Comment by melpon** [comment]
今の実装はそもそも `cpp example` を見る実装になっていないので、そこから直す必要があります。
その辺直せば動くと思うのでやっておきます。

**Comment by melpon** [comment]
対応に時間が掛かるかもしれないので、アドホックな対応が可能ならやって貰ってても大丈夫です。

**Comment by melpon** [comment]
多分直りました https://github.com/cpprefjp/kunai/commit/582a94dc34b673c8ac3b750f6dbed7562190e113

結構影響範囲の大きい部分を修正してるので、何か問題があれば教えて下さい。
