### ISSUE TITLE
[proposal]`noexcept`, `constexpr`をコードブロックでキーワードとして扱う

### ISSUE THREAD

**Issue by yumetodo** [cpprefjp/kunai#82]
`noexcept`, `constexpr`はキーワードのように扱ったほうが見やすくなるのではないか

**Comment by melpon** [comment]
これはどちらかというと `site_generator` 側の機能ですね。
シンタックスハイライトは `Pygments` でやっているのですが、今使っているのは 1.6 で、次のバージョンの 2.0 以降なら `constexpr` や `noexcept` に対応しているようです。
多分 [Python 3 に移行する](https://github.com/cpprefjp/site_generator/issues/54) と一緒にライブラリのバージョンを上げると思うので、そうしたら対応できるかなと思います。

**Comment by melpon** [comment]
ちゃんとキーワードとして扱われるようになったっぽいので閉じます
