### ISSUE TITLE
コードブロックの表示崩れ

### ISSUE THREAD

**Issue by faithandbrave** [cpprefjp/kunai#84]
https://cpprefjp.github.io/reference/filesystem/path/op_ostream.html

![2018-02-21 17 40 25](https://user-images.githubusercontent.com/240038/36470504-68425292-172e-11e8-8715-6abfee490c7e.png)

書き方は[`path/istream`](https://cpprefjp.github.io/reference/filesystem/path/op_istream.html)と同じにしてるはずなのですが、なぜかostreamの方だけ表示が壊れてます・・・。

**Comment by melpon** [comment]
あー、多分同じ内容のサンプルコードが２つあるからですね。id 作るためにコードブロックのハッシュ値を使ってるせいで、同じ id になってしまってるみたいです。
何番目のコードか、という情報も一緒に混ぜてハッシュ化するように直しておきます。

**Comment by faithandbrave** [comment]
naruhodo...

**Comment by faithandbrave** [comment]
修正よろしくお願いします！

**Comment by melpon** [comment]
直ったっぽいので閉じます

**Comment by faithandbrave** [comment]
ありがとうございます！
